stack:
  redshift: 0.5
  load_field: true
  save_field: false

  stack_field: false # If false, stacks maps instead of fields
  rad_distance: 1.0 # in arcmin
  min_radius: 1.0 # in rad_distance units
  max_radius: 6.0 # in rad_distance units
  num_radii: 11 # Number of radial bins between min_radius and max_radius

  mask_haloes: false
  mask_radii: 3.0 # Number of virial radii to mask out for haloes. In units of R200c
  
  projection: 'yz' # 'xy', 'xz', 'yz'
  pixel_size: 0.2 # in arcmin
  filter_type: 'DSigma' # Options: 'CAP', 'cumulative', 'DSigma'
  particle_type: 'total'

  filter_type_2: 'DSigma' # Options: 'CAP', 'cumulative', 'DSigma'
  particle_type_2: 'total'

plot:
  plot_data: True
  # data_path: '../data/Fig1_Fig8_dr10_allfoot_perbin_dr6_pzbin1.npz'
  data_path: '/pscratch/sd/r/rhliu/projects/Weak_lensing/hsc/products/spec_Y3/dsigma_tomo_noboost_hscy3_bin4_LRG_bin1.fits'
  data_label: 'HSCY3 Bin3 x LRG bin1 Lensing'
  fig_path: '../figures/'
  fig_name: 'hi_res_map_yz'
  fig_type: 'png'
  plot_error_bars: true


simulations:
  - sim_type: 'SIMBA'
    sims:
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50'
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50noagn'
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50nox'
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50nojet'
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50nofb'
      - name: 'm100n1024'
        snapshot: 125
        feedback: 's50'
  - sim_type: 'IllustrisTNG'
    sims:
      - name: 'TNG100-1'
        snapshot: 67
      - name: 'TNG300-1'
        snapshot: 67
      - name: 'TNG300-2'
        snapshot: 67
      - name: 'Illustris-1'
        snapshot: 103
      - name: 'Illustris-2'
        snapshot: 103